export const copies = {
    titleAuthStart: 'Te damos la bienvenida a ChatApp',
    descriptionAuthCaution: 'Recomendamos usar este servicio con responsabilidad para disfrutat de la experiencia que proporciona esta app desarrollada con cariño',
    descriptionAuthConsutation: 'Consulta nuestas Políticas de privacidad. Pulsa "Aceptar y continuar para aceptar las condiciones del servicio',
    acceptAuth: 'Aceptar y continuar',
    titleLogin: 'Entra y comienza a chatear',
    registerButton: 'Registrarse',
    infoLogin: 'Debes de tener al menos 16 años de edad para registrarte. Mas información sobre cómo trabaja ChatAPP en las politicas',
    titleRegisterScreen: 'Crea tu cuenta y empieza a enviar mensajes',
    startSession: 'Iniciar sesión',
    email: 'Correo Electronico',
    password: 'Contraseña',
    createAccount: 'Crear cuenta',
    send: 'Entrar',
    endSession: 'Cerrar sesión',
    changePicture: 'Cambiar foto de perfil',
    changeName: 'Cambiar nombre',
    changeLastname: 'Cambiar apellidos',
    name: 'Nombre',
    change: 'Cambiar',
    lastname: 'Apellidos',
    search: 'Buscar',
    charging: 'Cargando',
    noChats: 'No tienes ningun chat, dale al (+) y empieza una nueva conversación',
    loremIpsum: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.',
    delete: 'Eliminar',
    deleteChat: 'Eliminar Chat',
    deleteChateMessage: '¿Estás seguro de que quieres eliminar el chat con',
    deleteChateMessageV2: '¿Estás seguro de que quieres eliminar el chat?',
    cancel: 'Cancelar',
    sendMessage: 'Enviar un mensaje...',
    gallery: 'Galería',
    camera: 'Cámara',
    errorCamera: 'No has aceptado los permisos de la camara',
    groupName: 'Nombre del grupo',
    groupDontExist: 'No tienes nungún grupo, dale al (+) para crear el primero',
    exitGroup: 'Salir del grupo',
    participants: 'Participantes',
    addParticipants: 'Añadir participante'
};
